config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#show'

  resources :actors, only: [] do
    collection do
      get :big_movies
    end
  end

  resources :movies, only: [:index, :show] do
    collection do
      get :high_rated
      get :letters
      get :popular
    end
  end

  resources :directors, only: [:index] do
    collection do
      get :actors
    end
  end

  resources :memo, only: [:index]
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :roles
  has_many :movies, through: :roles, source: :actor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director

  has_many :roles
  has_many :actors, through: :roles, source: :actor
  has_many :votes
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :actor
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def big_movies
    @actors = []

    #TODO: Actors who played in big cast movies
    # Big cast movie = more than 30 actors per movie.
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @movie = Movie.first
  end

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController

  def index
    @movies = scope
  end

  def actors
    @directors = []
  end

  private

  def scope
    Movie.page(params[:page]).per(100).order(:id)
  end

end

app/controllers/memo_controller.rb
class MemoController < ApplicationController

  def index
    @movie = Movie.first
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = scope
  end

  def show
    @movie  = Movie.find(params[:id])
    @actors = @movie.actors
    @votes  = @movie.votes
  end

  def high_rated
    @movies = scope

    #TODO: get high rated movies
    # High rated movie = any movie with the score higher than or equal to 6.
  end

  def letters
    @letters = []

    #TODO: get movies count per starting letter
  end

  def popular
    @movies = []

    #TODO: get popular movies
    # Top movie     = movie with the highest votes count
    # Popular movie = its votes count is the same or smaller by maxium of 10 votes compared to the top movie
  end

  private

  def scope
    Movie.page(params[:page]).per(100).order(:id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def vote_score(value)
    number_with_precision value, precision: 1
  end

  def log_debug(text)
    Rails.logger.debug(text)
  end

end

app/views/actors/big_movies.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_item.html.erb
<li>
  <%= title %>.

  <blockquote>
    <%= hint %>.
  </blockquote>

  <p>
    <ul>
      <%- links.each_with_index do |link, index| %>
        <li>
          <%= link_to "Implementation ##{index + 1}", link %>
        </li>
      <%- end %>
    </ul>
  </p>
</li>

app/views/dashboard/show.html.erb
<ol>
  <%= render 'item',
        title: 'Movies index with director',
        hint: 'Using includes for eager loading',
        links: [directors_path] %>

  <%= render 'item',
        title: 'Movies show with details',
        hint: 'Using includes for eager loading with single resource',
        links: [movie_path(@movie)] %>

  <%= render 'item',
        title: 'Association memoization',
        hint: 'Caching relationships',
        links: [memo_index_path] %>

  <%= render 'item',
        title: 'Movies index with scoring',
        hint: 'Using average to calculate score for each movie in the list',
        links: [movies_path] %>

  <%= render 'item',
        title: 'Movies count by letters',
        hint: 'Grouping movies by letter',
        links: [letters_movies_path] %>

  <%= render 'item',
        title: 'High rated movies with scoring',
        hint: 'Using having to match based on the result of aggregation functions',
        links: [high_rated_movies_path] %>

  <%= render 'item',
        title: 'Director with movies whereas its actors name start with letter T',
        hint: 'Using distinct to eliminate duplicates',
        links: [actors_directors_path] %>

  <%= render 'item',
        title: 'Actors who played in big cast movies',
        hint: 'Using nested queries',
        links: [big_movies_actors_path] %>

  <%= render 'item',
        title: 'Popular movies',
        hint: 'Using nested queries',
        links: [popular_movies_path] %>
</ol>

app/views/directors/actors.html.erb
<table>
  <thead>
    <tr>
      <th>Director</th>
    </tr>
  </thead>
  <tbody>
    <% @directors.each do |director| %>
      <tr>
        <td><%= director.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/directors/index.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Director</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>#<%= movie.id %></td>
        <td><%= movie.title %></td>
        <td><%= movie.director.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movietape</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memo/_01_relationships.html.erb
<%- 2.times do |i| %>
  <% log_debug "\ndirector #{i} {" %>

  <h3>
    directed by
    <%= @movie.director.name %>
  </h3>

  <% log_debug "}\n" %>
<% end %>

<%- 2.times do |i| %>
  <% log_debug "\nactors #{i} {" %>

  <h3>Actors:</h3>
  <table>
    <tbody>
      <% @movie.actors.each do |actor| %>
        <tr>
          <td><%= actor.id %></td>
          <td><%= actor.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% log_debug "}\n" %>
<% end %>

app/views/memo/_02_ids.html.erb
<%- 2.times do |i| %>
  <% log_debug "\nactor IDS #{i} {" %>

  <h3>Actor IDS:</h3>
  <table>
    <tbody>
      <% @movie.actor_ids.each do |id| %>
        <tr>
          <td><%= id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% log_debug "}\n" %>
<% end %>

app/views/memo/_03_pluck.html.erb
<%- 2.times do |i| %>
  <% log_debug "\npluck #{i} {" %>

  <h3>Actors:</h3>
  <table>
    <tbody>
      <% @movie.actors.pluck(:id, :name).each do |id, name| %>
        <tr>
          <td><%= id %></td>
          <td><%= name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% log_debug "}\n" %>
<% end %>

app/views/memo/_04_pluck_uncached.html.erb
<%- Movie.uncached do %>
  <%- 2.times do |i| %>
    <% log_debug "\npluck uncached #{i} {" %>

    <h3>Actors:</h3>
    <table>
      <tbody>
        <% @movie.actors.pluck(:id, :name).each do |id, name| %>
          <tr>
            <td><%= id %></td>
            <td><%= name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <% log_debug "}\n" %>
  <% end %>
<% end %>

app/views/memo/_05_actors_uncached.html.erb
<%- Movie.uncached do %>
  <%- 2.times do |i| %>
    <% log_debug "\nactors uncached #{i} {" %>

    <h3>Actors:</h3>
    <table>
      <tbody>
        <% @movie.actors.each do |actor| %>
          <tr>
            <td><%= actor.id %></td>
            <td><%= actor.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <% log_debug "}\n" %>
  <% end %>
<% end %>

app/views/memo/_06_pluck_after_actors.html.erb
<% log_debug "\nactors {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.each do |actor| %>
      <tr>
        <td><%= actor.id %></td>
        <td><%= actor.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>


<% log_debug "\npluck {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.pluck(:id, :name).each do |id, name| %>
      <tr>
        <td><%= id %></td>
        <td><%= name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>

app/views/memo/_07_pluck_before_actors.html.erb
<% log_debug "\npluck {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.pluck(:id, :name).each do |id, name| %>
      <tr>
        <td><%= id %></td>
        <td><%= name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>


<% log_debug "\nactors {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.each do |actor| %>
      <tr>
        <td><%= actor.id %></td>
        <td><%= actor.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>

app/views/memo/_08_pluck_before_actors_with_select.html.erb
<% log_debug "\npluck {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.pluck(:id, :name).each do |id, name| %>
      <tr>
        <td><%= id %></td>
        <td><%= name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>


<% log_debug "\nactors {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.select(:id, :name).each do |actor| %>
      <tr>
        <td><%= actor.id %></td>
        <td><%= actor.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>

app/views/memo/_09_ids_after_actors.html.erb
<% log_debug "\nactors {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.each do |actor| %>
      <tr>
        <td><%= actor.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>


<% log_debug "\ids {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actor_ids.each do |id| %>
      <tr>
        <td><%= id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>

app/views/memo/_10_ids_before_actors.html.erb
<% log_debug "\ids {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actor_ids.each do |id| %>
      <tr>
        <td><%= id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>


<% log_debug "\nactors {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.each do |actor| %>
      <tr>
        <td><%= actor.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>

app/views/memo/_11_ids_before_pluck.html.erb
<% log_debug "\ids {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actor_ids.each do |id| %>
      <tr>
        <td><%= id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>


<% log_debug "\npluck {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.pluck(:id) do |id| %>
      <tr>
        <td><%= id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>

app/views/memo/_12_ids_after_pluck.html.erb
<% log_debug "\npluck {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.pluck(:id) do |id| %>
      <tr>
        <td><%= id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>


<% log_debug "\ids {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actor_ids.each do |id| %>
      <tr>
        <td><%= id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>

app/views/memo/_13_pluck_star.html.erb
<% log_debug "\npluck {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.pluck('*').each do |id, name, _, _| %>
      <tr>
        <td><%= id %></td>
        <td><%= name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>


<% log_debug "\nactors {" %>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @movie.actors.each do |actor| %>
      <tr>
        <td><%= actor.id %></td>
        <td><%= actor.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% log_debug "}\n" %>

app/views/memo/index.html.erb
<h2>
  <%= @movie.title %>
</h2>

<%# NOTE: Make sure to render only one to see the correct result or reload model between each render. %>
<%# <%= render '01_relationships' %1> %>
<%# <%= render '02_ids' %1> %>
<%# <%= render '03_pluck' %1> %>
<%# <%= render '04_pluck_uncached' %1> %>
<%# <%= render '05_actors_uncached' %1> %>
<%# <%= render '06_pluck_after_actors' %1> %>
<%# <%= render '07_pluck_before_actors' %1> %>
<%# <%= render '08_pluck_before_actors_with_select' %1> %>
<%# <%= render '09_ids_after_actors' %1> %>
<%# <%= render '10_ids_before_actors' %1> %>
<%# <%= render '11_ids_before_pluck' %1> %>
<%# <%= render '12_ids_after_pluck' %1> %>
<%# <%= render '13_pluck_star' %1> %>

app/views/movies/high_rated.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>#<%= movie.id %></td>
        <td><%= movie.title %></td>
        <td><%= vote_score movie.votes.average(:rating) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/index.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Rating</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>#<%= movie.id %></td>
        <td><%= movie.title %></td>
        <td><%= vote_score movie.votes.average(:rating) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/letters.html.erb
<table>
  <thead>
    <tr>
      <th>Letter</th>
      <th>Total movies</th>
    </tr>
  </thead>
  <tbody>
    <% @letters.each do |_| %>
      <tr>
        <td><%= "TODO: letter" %></td>
        <td><%= "TODO: count" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/popular.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>#<%= movie.id %></td>
        <td><%= movie.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/show.html.erb
<h2>
  <%= @movie.title %>
</h2>

<h3>
  directed by
  <%= @movie.director.name %>
</h3>

<h3>Actors:</h3>
<table>
  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Votes:</h3>
<table>
  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.user.name %></td>
        <td><%= vote_score vote.rating %></td>
      </tr>
    <% end %>
  </tbody>
</table>